<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <!----------------BANNER DE DEDICATORIA------------------------------------->
                <table class="artist-photo">
                    <tr>
                        <td class="artist" colspan=3 >
                            <div class="artist-text">

                                <div class="title-img">
                                    <a class="text-title" style="font-size:15px"
                                       >Movil no ha sido detectado. No es posible acceder al sitio.
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: orange">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: white;font-size:18px"
                                       href="http://m.entretenimiento.entel.pe">ENTRETENIMIENTO ENTEL
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <br>

            </div>
        </div>
    </div>
</div>
